on:
  push:
    branches:
      - main

jobs:
  check:
    name: Deploy stack
    runs-on: ubuntu-latest
    steps:
      - name: AWS CloudFormation "Deploy CloudFormation Stack" Action for GitHub Actions
        uses: aws-actions/aws-cloudformation-github-deploy@v1


